title: Return to Home Page
description: Welcome to my website. Please make yourself cozy.
theme: jekyll-theme-minimal

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
